name: Deploy Minecraft Server

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      # Paso para hacer checkout del código
      - name: Checkout code
        uses: actions/checkout@v2

      # Paso para instalar Java 17
      - name: Install Java
        run: sudo apt-get update && sudo apt-get install -y openjdk-17-jre-headless

      # Verificar si server.jar existe
      - name: Verify if server.jar exists
        run: |
          if [ ! -f server.jar ]; then
            echo "server.jar not found!"
            exit 1
          fi

      # Paso para ejecutar el servidor de Minecraft con 4GB de RAM
      - name: Start Minecraft Server
        run: |
          java -Xmx4096M -Xms4096M -jar server.jar nogui
